-- Dish table seeds here
INSERT INTO dishes (name, price, calorie, type, photo_url, description) VALUES
--pizzas
('THE ORIGINAL BBQ CHICKEN PIZZA', 2099, 190, 'pizza', 'https://d1ralsognjng37.cloudfront.net/0c9767c4-442b-4715-ab37-476a61ba2aaf.jpeg', 'Created here in 1985. Our legendary BBQ sauce, smoked Gouda, red onions and fresh cilantro transform this original to iconic. Also available with Nueskes applewood smoked bacon or fresh pineapple. [Calories listed are per slice. All pizzas are 6 slices.]'),
('WILD MUSHROOM', 1999, 170, 'pizza', 'https://d1ralsognjng37.cloudfront.net/d1bf464f-7121-4002-97f1-84b0fd55d815.jpeg', 'Shaved Cremini, Shiitake, and Portobello mushrooms with slivered scallions, cracked black pepper, Romano and Mozzarella. Finished with Parmesan. Also available with white truffle oil. [Calories listed are per slice. All pizzas are 6 slices.]'),
('HAWAIIAN', 2199, 180, 'pizza', 'https://d1ralsognjng37.cloudfront.net/810e5b8d-c0c4-4275-84bc-38a7e52a3607.jpeg', 'Fresh pineapple, applewood smoked ham and slivered scallions. [Calories listed are per slice. All pizzas are 6 slices.]'),
('FIVE CHEESE + FRESH TOMATO', 1999, 190, 'pizza', 'https://d1ralsognjng37.cloudfront.net/9df52a04-5fbc-4d8b-8f92-2e74d5a772a8.jpeg', 'Fresh and traditional Mozzarella, Monterey Jack, smoked Gouda and Romano with tomato and fresh basil. [Calories listed are per slice. All pizzas are 6 slices.]'),
('SPICY CHIPOTLE CHICKEN', 2199, 220, 'pizza', 'https://d1ralsognjng37.cloudfront.net/b02fc0c7-5519-4082-a381-681d60a93596.jpeg', 'Chipotle adobo sauce, shaved poblanos and Monterey Jack with housemade roasted corn & black bean salsa, fresh cilantro and tangy lime crema. [Calories listed are per slice. All pizzas are 6 slices.]'),
('CALIFORNIA CLUB', 2299, 220, 'pizza', 'https://d1ralsognjng37.cloudfront.net/cd296bbd-c322-4512-b5ab-9a7ccab54230.jpeg', 'Nueskes applewood smoked bacon, grilled chicken and Mozzarella, hearth-baked then topped with avocado, wild arugula, fresh tomatoes, torn basil and Romaine tossed in lemon-pepper mayo. [Calories listed are per slice. All pizzas are 6 slices.]'),
('SHRIMP SCAMPI PIZZA', 2199, 190, 'pizza', 'https://d1ralsognjng37.cloudfront.net/fa630149-bf30-4876-8f6f-03aec857bece.jpeg', 'Housemade lemon-garlic shrimp with caramelized onions, Mozzerella, Parmesan and red chili, topped with fresh arugula and wild Greek oregano. Suggested on cauliflower crust. [Calories listed are per slice. All pizzas are 6 slices.]'),
('CALIFORNIA VEGGIE', 2099, 180, 'pizza', 'https://d1ralsognjng37.cloudfront.net/0a206e3c-5682-4bb4-b73d-96bbd60e5ba2.jpeg', 'Broccolini, eggplant, Cremini mushrooms, sun-dried tomatoes, roasted corn, red onions and Mozzarella. Also available with goat cheese. [Calories listed are per slice. All pizzas are 6 slices.]'),
('PEPPERONI', 2099, 190, 'pizza', 'https://d1ralsognjng37.cloudfront.net/220a3459-4e2f-4587-bad2-45bce6a83e4c.jpeg', 'Rustic and spicy pepperoni with fresh Mozzarella and wild Greek oregano. Also available with white truffle oil. [Calories listed are per slice. All pizzas are 6 slices.]'),
('ROASTED GARLIC CHICKEN', 2199, 230, 'pizza', 'https://d1ralsognjng37.cloudfront.net/2be3811b-16ad-4419-8c74-371124eedd1a.jpeg', 'Sweet caramelized onions, fresh Mozzarella, Parmesan, slivered scallions and cracked black pepper. Suggested on cauliflower crust. [Calories listed are per slice. All pizzas are 6 slices.]'),
('SPICY MILANO', 2099, 240, 'pizza', 'https://d1ralsognjng37.cloudfront.net/0740e526-1826-4813-b9dd-8baebf3fb2be.jpeg', 'Spicy marinara, serrano peppers, Italian sausage, spicy pepperoni, Cremini mushrooms, yellow onions, fresh Mozzarella & Romano and wild Greek oregano. [Calories listed are per slice. All pizzas are 6 slices.]'),
('TOSTADA PIZZA', 2099, 190, 'pizza', 'https://d1ralsognjng37.cloudfront.net/a5e1bcb5-6333-49d6-8bbd-19dd36b73093.jpeg', 'Crisp lettuce, tortilla strips and housemade herb ranch top this hearth-baked crust with layers of black beans, and Monterey Jack. Served with flame-roasted salsa. Also available with lime chicken or carne asada. [Calories listed are per slice. All pizzas are 6 slices.]'),
('MARGHERITA', 1999, 220, 'pizza', 'https://d1ralsognjng37.cloudfront.net/9ae8f61d-e2f3-4dcd-ad44-34b983c38e81.jpeg', 'Crushed tomatoes with fresh Mozzarella, fresh basil and Parmesan. [Calories listed are per slice. All pizzas are 6 slices.]'),
--salads
('THE ORIGINAL BBQ CHICKEN CHOPPED SALAD', 1599, 1180, 'salad', 'https://d1ralsognjng37.cloudfront.net/1a2a1234-666f-415f-8a0c-6e198eb15104.jpeg', 'Black beans, sweet corn, jicama, fresh cilantro & basil, crispy corn tortilla strips, Monterey Jack and our housemade herb ranch on the side. Topped with tomatoes and scallions. Also available with fresh avocado.'),
('ROASTED VEGGIE', 1699, 730, 'salad', 'https://d1ralsognjng37.cloudfront.net/0474ee89-5b4c-4f5c-8f10-a3fb03b1a3ca.jpeg', 'Warm artichoke hearts, asparagus, eggplant, red & yellow peppers, corn and sun-dried tomatoes served with cool Romaine, avocado and housemade Dijon balsamic vinaigrette. Also available with grilled chicken, shrimp or sautéed salmon.'),
('CLASSIC CAESAR', 1299, 530, 'salad', 'https://d1ralsognjng37.cloudfront.net/d40a2c12-79fb-40c6-bafa-a8ab65809876.jpeg', 'Crisp Romaine with shaved Parmesan and housemade garlic butter croutons. Also available with grilled chicken, shrimp, or sautéed salmon.'),
('THAI CRUNCH', 1799, 1180, 'salad', 'https://d1ralsognjng37.cloudfront.net/eb52c4eb-e606-4446-813f-1c5213755b9f.jpeg', 'Crisp veggies and fresh cilantro with chicken and the crunch of peanuts, wontons and rice sticks. Served with Thai peanut dressing. Also available with fresh avocado.'),
('ITALIAN CHOPPED', 1699, 1010, 'salad', 'https://d1ralsognjng37.cloudfront.net/68b2d482-7d58-4a63-87a0-0cbdb299a70a.jpeg', 'Roasted turkey breast, julienned salami, garbanzo beans, tomatoes, Mozzarella and fresh basil. Served with housemade mustard herb vinaigrette.'),
('CRISPY ARTICHOKE SALAD', 999, 350, 'salad', 'https://d1ralsognjng37.cloudfront.net/1f18b2ec-7171-4d3d-9bc9-507ee011dfc1.jpeg', 'Crispy artichoke hearts with whipped goat cheese, arugula and Parmesan served with our housemade Champagne vinaigrette.'),
('BANH MI POWER BOWL', 2099, 540, 'salad', 'https://d1ralsognjng37.cloudfront.net/615b2722-e44f-470d-8ffe-da5dc76283a1.jpeg', 'Quinoa, baby kale, fresh cilantro & mint topped with grilled chicken, watermelon radish, fresh avocado, cucumber, carrot, bean sprouts, scallions and sesame seeds. Served with housemade chili-lime vinaigrette and serrano peppers.'),
('SANTA FE POWER BOWL', 2099, 690, 'salad', 'https://d1ralsognjng37.cloudfront.net/e366284d-bd5f-4f55-a8ec-536a2da2e174.jpeg', 'Cilantro farro and spinach topped with lime chicken, tomatoes, sweet corn, black beans, red cabbage, fresh avocado, poblano peppers and toasted pepitas. Served with housemade poblano ranch on the side.');
